## Question 4

In [3]:
import pandas as pd
from ipykernel import kernelapp as app
from pandas import Series, DataFrame
a = pd.read_csv('C:\\Users\mites\Python\DataAnalysis4Python_Spring17\Assignments\Assignment 3\Data\\movies_awards.csv')
a[:5]

,totalSeasons,Plot,Rated,Response,Language,Title,Country,Writer,Metascore,imdbRating,...,Released,Actors,Year,Genre,Awards,Runtime,Type,Poster,imdbVotes,imdbID
0,none,NaN,NaN,True,English,Book of Love: The Definitive Reason Why Men Ar...,USA,Jeffrey W. Byrd; Eric George,NaN,6.6,...,14 Feb 2002,40 Glocc; Angelle Brooks; David Brown; Qadr Ca...,2002,Romance; Comedy,NaN,91 min,movie,NaN,79.0,tt0156376
1,none,NaN,NaN,True,Swedish,Anderssons älskarinna,Sweden,NaN,NaN,7.4,...,12 Feb 2001,Jakob Eklund; Ebba Forsberg; Örjan Landström; ...,2001,Drama,NaN,347 min,movie,NaN,34.0,tt0201374
2,none,NaN,NaN,True,English,Bad Blood,UK,Tony Marchant,NaN,5.6,...,11 Jan 2001,Emilia Fox; Serban Celea; Alex Jennings; Steve...,2001,NaN,NaN,NaN,movie,NaN,8.0,tt0207989
3,none,A historical classic drama in three acts; reto...,NaN,True,Portuguese,Who Are You?,Portugal,João Botelho; Almeida Garrett (play),NaN,6.1,...,23 Nov 2001,Patrícia Guerreiro; Suzana Borges; Rui Morisso...,2001,Drama; History,1 win & 2 nominations.,112 min,movie,http://ia.media-imdb.com/images/M/MV5BMTM1Mjdi...,189.0,tt0210930
4,none,A father (Williams) suspects his son (Jackson)...,R,True,English,Skeletons in the Closet,USA,Donna Powers; Wayne Powers,NaN,5.4,...,24 Jul 2001,Treat Williams; Linda Hamilton; Jonathan Jacks...,2001,Crime; Drama; Mystery,1 win.,100 min,movie,http://ia.media-imdb.com/images/M/MV5BMjA0NjA2...,603.0,tt0212513

In [20]:
frame = DataFrame(a, columns=['Awards'])
frame[:10]

                    Awards
0                      NaN
1                      NaN
2                      NaN
3   1 win & 2 nominations.
4                   1 win.
5            1 nomination.
6  3 wins & 2 nominations.
7    1 win & 1 nomination.
8                      NaN
9                      NaN

In [22]:
#frame['AwardsWon'] = frame[frame['Awards'].str.contains("win")]
frame['AwardsWon'] = frame['Awards'].str.extract('(\d+) win', expand=True)
frame['AwardsNominated'] = frame['Awards'].str.extract('(\d+) nomination', expand=True)
frame['PrimeAwardsWon']= frame['Awards'].str.extract('Won (\d+) Primetime', expand=True)
frame['PrimeAwardsNominated']= frame['Awards'].str.extract('Nominated for (\d+) Primetime', expand=True)
frame['BaftaAwardsWon']= frame['Awards'].str.extract('Won (\d+) BAFTA', expand=True)
frame['BaftaAwardsNominated']= frame['Awards'].str.extract('Nominated for (\d+) BAFTA', expand=True)
frame['OscarAwardsWon']= frame['Awards'].str.extract('Won (\d+) Oscar', expand=True)
frame['OscarAwardsNominated']= frame['Awards'].str.extract('Nominated for (\d+) Oscar', expand=True)
frame['GoldenGlobeAwardsWon']= frame['Awards'].str.extract('Won (\d+) Golden Globe', expand=True)
frame['GoldenGlobeAwardsNominated']= frame['Awards'].str.extract('Nominated for (\d+) Golden Globe', expand=True)

In [36]:
frame2 = frame.fillna(0)

In [29]:
frame2['AwardsWon'] = frame2['AwardsWon'].astype(str).astype(int)
frame2['AwardsNominated'] = frame2['AwardsNominated'].astype(str).astype(int) 
frame2['PrimeAwardsWon'] = frame2['PrimeAwardsWon'].astype(str).astype(int)
frame2['PrimeAwardsNominated'] = frame2['PrimeAwardsNominated'].astype(str).astype(int)
frame2['BaftaAwardsWon'] = frame2['BaftaAwardsWon'].astype(str).astype(int) 
frame2['BaftaAwardsNominated'] = frame2['BaftaAwardsNominated'].astype(str).astype(int)
frame2['OscarAwardsWon'] = frame2['OscarAwardsWon'].astype(str).astype(int) 
frame2['OscarAwardsNominated'] = frame2['OscarAwardsNominated'].astype(str).astype(int) 
frame2['GoldenGlobeAwardsWon'] = frame2['GoldenGlobeAwardsWon'].astype(str).astype(int) 
frame2['GoldenGlobeAwardsNominated'] = frame2['GoldenGlobeAwardsNominated'].astype(str).astype(int)

In [35]:
frame2['TotalAwardsWon'] = frame2['AwardsWon']+frame2['PrimeAwardsWon']+frame2['BaftaAwardsWon']+frame2['OscarAwardsWon']+frame2['GoldenGlobeAwardsWon']
frame2['TotalAwardsNominated'] = frame2['AwardsNominated']+frame2['PrimeAwardsNominated']+frame2['BaftaAwardsNominated']+frame2['OscarAwardsNominated']+frame2['GoldenGlobeAwardsNominated']
frame3 = frame2.loc[~frame2.apply(lambda row: (row==0).all(), axis=1)]
frame3

,Awards,AwardsWon,AwardsNominated,PrimeAwardsWon,PrimeAwardsNominated,BaftaAwardsWon,BaftaAwardsNominated,OscarAwardsWon,OscarAwardsNominated,GoldenGlobeAwardsWon,GoldenGlobeAwardsNominated,TotalAwardsWon,TotalAwardsNominated
3,1 win & 2 nominations.,1,2,0,0,0,0,0,0,0,0,1,2
4,1 win.,1,0,0,0,0,0,0,0,0,0,1,0
5,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
6,3 wins & 2 nominations.,3,2,0,0,0,0,0,0,0,0,3,2
7,1 win & 1 nomination.,1,1,0,0,0,0,0,0,0,0,1,1
11,5 nominations.,0,5,0,0,0,0,0,0,0,0,0,5
13,2 wins & 5 nominations.,2,5,0,0,0,0,0,0,0,0,2,5
15,Nominated for 1 Oscar. Another 13 wins & 13 no...,13,13,0,0,0,0,0,1,0,0,13,14
18,5 wins & 4 nominations.,5,4,0,0,0,0,0,0,0,0,5,4
24,Nominated for 1 Golden Globe. Another 14 wins ...,14,34,0,0,0,0,0,0,0,1,14,35
25,3 wins & 2 nominations.,3,2,0,0,0,0,0,0,0,0,3,2
28,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
31,5 nominations.,0,5,0,0,0,0,0,0,0,0,0,5
34,1 win & 2 nominations.,1,2,0,0,0,0,0,0,0,0,1,2
37,22 wins & 44 nominations.,22,44,0,0,0,0,0,0,0,0,22,44
38,1 win & 3 nominations.,1,3,0,0,0,0,0,0,0,0,1,3
39,1 win & 8 nominations.,1,8,0,0,0,0,0,0,0,0,1,8
43,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
47,6 wins & 1 nomination.,6,1,0,0,0,0,0,0,0,0,6,1
50,Won 2 Golden Globes. Another 68 wins & 201 nom...,68,201,0,0,0,0,0,0,2,0,70,201
51,Won 1 Golden Globe. Another 31 wins & 143 nomi...,31,143,0,0,0,0,0,0,1,0,32,143
53,Nominated for 4 Primetime Emmys. Another 16 no...,0,16,0,4,0,0,0,0,0,0,0,20
54,3 wins & 2 nominations.,3,2,0,0,0,0,0,0,0,0,3,2
56,3 wins & 6 nominations.,3,6,0,0,0,0,0,0,0,0,3,6
62,2 wins.,2,0,0,0,0,0,0,0,0,0,2,0
69,6 wins & 4 nominations.,6,4,0,0,0,0,0,0,0,0,6,4
72,7 wins & 6 nominations.,7,6,0,0,0,0,0,0,0,0,7,6
76,9 wins & 30 nominations.,9,30,0,0,0,0,0,0,0,0,9,30
79,Won 1 Primetime Emmy. Another 1 win & 6 nomina...,1,6,1,0,0,0,0,0,0,0,2,6
84,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13668,1 win.,1,0,0,0,0,0,0,0,0,0,1,0
13669,5 wins.,5,0,0,0,0,0,0,0,0,0,5,0
13699,1 win.,1,0,0,0,0,0,0,0,0,0,1,0
13727,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
13879,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
13898,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
13997,1 win.,1,0,0,0,0,0,0,0,0,0,1,0
14003,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
14007,1 win.,1,0,0,0,0,0,0,0,0,0,1,0
14046,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
14089,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
14136,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
14137,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
14249,2 wins & 2 nominations.,2,2,0,0,0,0,0,0,0,0,2,2
14346,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
14432,2 wins & 2 nominations.,2,2,0,0,0,0,0,0,0,0,2,2
14599,2 wins & 1 nomination.,2,1,0,0,0,0,0,0,0,0,2,1
14652,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
14761,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
14792,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
14800,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
14805,1 win.,1,0,0,0,0,0,0,0,0,0,1,0
14873,1 win.,1,0,0,0,0,0,0,0,0,0,1,0
14908,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
15177,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
15180,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
15219,2 nominations.,0,2,0,0,0,0,0,0,0,0,0,2
15230,1 nomination.,0,1,0,0,0,0,0,0,0,0,0,1
15234,1 win & 1 nomination.,1,1,0,0,0,0,0,0,0,0,1,1
15269,7 nominations.,0,7,0,0,0,0,0,0,0,0,0,7

In [39]:
frame4 = frame3.head(5).to_csv('awards.csv')
frame4